### PR TITLE
Fixed template name

### PR DESCRIPTION
**Pull request by mguillem**
There is no letsencrypt-template.yaml file in the project

### CODE REVIEW

**Comment by ibotty** [comment]
have you tested the role assignement? AFAICT it won't work as is, because get_certificate will try to get the acme secret (which will fail when admin rights are not granted).

Of course, one could mount the secret in the pod (has to be added to the template) and remove that part.

**Comment by ibotty** [comment]
I forgot: thank you for contributing!

**Comment by mguillem** [comment]
This is the role assignment that works for me on two different openshift installations:

openshift v1.3.1
kubernetes v1.3.0+52492b4

openshift v3.4.1.2
kubernetes v1.4.0+776c994

Btw: great tool! Thanks.
An appropriate error message if routes can't be retrieved due to missing rights would have helped in my case.

**Comment by mguillem** [comment]
Seems that my previous code was not really the right one. It worked but I don't understand why. This one makes sense to me and is working correctly:
```
oc policy add-role-to-user edit system:serviceaccount:`oc project -q`:letsencrypt
```

**Pull request merged**
